#pragma once

namespace ObjID
{
	enum ID { HOLE, SHADOW, LOWERDETAIL, STONE, BOSS_BULLET, BOSS, BOSS_ARM, MONSTER, SHOP, PLAYER, WEAPON, PLAYER_BULLET, MONSTER_BULLET, EFFECT, DOOR, UI, MOUSE, END };
}

namespace GroupID
{
	enum ID {SHADOW, BACKGROUND, GAMEOBJECT, EFFECT, UI, END};
}
